const AzureData = [
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Virginia-2cpu-4GB",
    AccessToken: "Bearer ...",
    MachineType: "2cpu-4GB",
    Location: "Virginia",
    MemorySize: 4,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Virginia-4cpu-16GB",
    AccessToken: "Bearer ...",
    MachineType: "4cpu-16GB",
    Location: "Virginia",
    MemorySize: 16,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Virginia-8cpu-32GB",
    AccessToken: "Bearer ...",
    MachineType: "8cpu-32GB",
    Location: "Virginia",
    MemorySize: 32,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "UK-2cpu-4GB",
    AccessToken: "Bearer ...",
    MachineType: "2cpu-4GB",
    Location: "UK",
    MemorySize: 4,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "UK-4cpu-16GB",
    AccessToken: "Bearer ...",
    MachineType: "4cpu-16GB",
    Location: "UK",
    MemorySize: 16,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "UK-8cpu-32GB",
    AccessToken: "Bearer ...",
    MachineType: "8cpu-32GB",
    Location: "UK",
    MemorySize: 32,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Japan-2cpu-4GB",
    AccessToken: "Bearer ...",
    MachineType: "2cpu-4GB",
    Location: "Japan",
    MemorySize: 4,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Japan-4cpu-16GB",
    AccessToken: "Bearer ...",
    MachineType: "4cpu-16GB",
    Location: "Japan",
    MemorySize: 16,
  },
  {
    SubscriptionId: "ea829b3c - bd87 - 4333 - a335 - 7b7ca2173dbd",
    ResourceGroupName: "CloudsCompare",
    VirtualMachineName: "Japan-8cpu-32GB",
    AccessToken: "Bearer ...",
    MachineType: "8cpu-32GB",
    Location: "Japan",
    MemorySize: 32,
  },
];

export default AzureData;
